// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#pragma once

#include "djinni_support.hpp"
#include "timer.hpp"

namespace djinni_generated {

class NativeTimer final : ::djinni::JniInterface<::cpptimer::Timer, NativeTimer> {
public:
    using CppType = std::shared_ptr<::cpptimer::Timer>;
    using JniType = jobject;

    using Boxed = NativeTimer;

    ~NativeTimer();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTimer>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<NativeTimer>::get()._toJava(jniEnv, c)}; }

private:
    NativeTimer();
    friend ::djinni::JniClass<NativeTimer>;
    friend ::djinni::JniInterface<::cpptimer::Timer, NativeTimer>;

};

}  // namespace djinni_generated
