// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

package com.mycompany.cpptimer;

public abstract class TimerListener {
    public abstract void timerTicked(int secondsRemaining);

    public abstract void timerEnded();
}
