// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

package com.mycompany.cpptimer;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Timer {
    public abstract void startTimer(int seconds);

    public static native Timer createWithListener(TimerListener listener);

    private static final class CppProxy extends Timer
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void startTimer(int seconds)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_startTimer(this.nativeRef, seconds);
        }
        private native void native_startTimer(long _nativeRef, int seconds);
    }
}
