// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#import "CPPTTimerListener+Private.h"
#import "CPPTTimerListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class TimerListener::ObjcProxy final
: public ::cpptimer::TimerListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void TimerTicked(int32_t c_seconds_remaining) override
    {
        @autoreleasepool {
            [Handle::get() timerTicked:(::djinni::I32::fromCpp(c_seconds_remaining))];
        }
    }
    void TimerEnded() override
    {
        @autoreleasepool {
            [Handle::get() timerEnded];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto TimerListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto TimerListener::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
