// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#import "CPPTTimer+Private.h"
#import "CPPTTimer.h"
#import "CPPTTimer+Private.h"
#import "CPPTTimerListener+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CPPTTimer ()

- (id)initWithCpp:(const std::shared_ptr<::cpptimer::Timer>&)cppRef;

@end

@implementation CPPTTimer {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cpptimer::Timer>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cpptimer::Timer>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable CPPTTimer *)createWithListener:(nullable id<CPPTTimerListener>)listener {
    try {
        auto r = ::cpptimer::Timer::CreateWithListener(::djinni_generated::TimerListener::toCpp(listener));
        return ::djinni_generated::Timer::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)startTimer:(int32_t)seconds {
    try {
        _cppRefHandle.get()->StartTimer(::djinni::I32::toCpp(seconds));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Timer::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Timer::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CPPTTimer>(cpp);
}

}  // namespace djinni_generated

@end
