// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#import <Foundation/Foundation.h>


@protocol CPPTTimerListener

- (void)timerTicked:(int32_t)secondsRemaining;

- (void)timerEnded;

@end
