// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#include "timer.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CPPTTimer;

namespace djinni_generated {

class Timer
{
public:
    using CppType = std::shared_ptr<::cpptimer::Timer>;
    using ObjcType = CPPTTimer*;

    using Boxed = Timer;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

