// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#pragma once

#include <cstdint>

namespace cpptimer {

class TimerListener {
public:
    virtual ~TimerListener() {}

    virtual void TimerTicked(int32_t seconds_remaining) = 0;

    virtual void TimerEnded() = 0;
};

}  // namespace cpptimer
