// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cpptimer.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace cpptimer {

class TimerListener;

class Timer {
public:
    virtual ~Timer() {}

    /** constructor */
    static std::shared_ptr<Timer> CreateWithListener(const std::shared_ptr<TimerListener> & listener);

    virtual void StartTimer(int32_t seconds) = 0;
};

}  // namespace cpptimer
